### ISSUE TITLE
Milestone 4 Discussion

### ISSUE THREAD

**Issue by LukeAC** [UBC-MDS/covid_reddit_behaviour#58]
COMMENTS SUMMARY
1. EDA (@MaeveShi):
- [x] Figure titles and axis labels(?)
- [x] Add a line or two of description for charts
- [x] Move EDA-summary file out of ./eda/subreddit into eda/
- [x] Additionally for the histograms, you could also maybe change the opacity to see overlaps between pre and post data.

2. Misc Additions (@LukeAC )
- [ ] ~Add info about Wilcoxon rank sum test~
- [x] Add more details about features in the dataset (including those not used)
- [x] Include raw/processed data

3.  Easy wins (@nobbynguyen )
- [x] Add author emails to Contribution
- [x] Add 'Make' instructions to ReadMe
- [x]  Delete 'Reference' section from README.md

**Comment by LukeAC** [comment]
FINAL TASKS:

@LukeAC - respond to feedback issue thread with changes made in response
@mel-liow  - Add 'Docker stuff' to README.md
@nobbynguyen  - Create another release for your project repo (1.0.0) and submit the following 3 links to Canvas:

- The URL of the release
- The URL of the repository
- The link to the issue where you received the project peer reviews and you have pasted the links to the commits.

**Comment by LukeAC** [comment]
Everyone should run the following commands in the project root locally:
1.
```console
make clean
```
2.
```console
make all
```

**Comment by mel-liow** [comment]
@nobbynguyen could you also address this please?

Important Some of you have chosen datasets that take ages to download and to perform analyses that take significant amount of computation resources and time. In your README, please clearly document that this is the case along with estimated completion times (on your machines is fine). This is so that the TAs are not stuck running these analyses for indeterminate amounts of time.

**Comment by nobbynguyen** [comment]
@mel-liow : Sure, I will do.

**Comment by LukeAC** [comment]
Hey guys - once you've completed your milestone 4 tasks could you please include the link to the associated PR and commit(s) here for me to be able to add them to our feedback response? Thanks.

I've also removed the requirement to add more detail on the Wilcoxon test as - in results.ipynb - there is already all the information required to satisfy this; i'm not sure what else he/she wants and am guessing they did not see this page.

**Comment by nobbynguyen** [comment]
Hi guys, I check the slides of Milestone3 [https://pages.github.ubc.ca/fdandrea/DSCI-522_milestone3/slides.html#30](url) it is also required that we should add our names to the License file. That is why I just made a commit to update License. [https://github.com/UBC-MDS/covid_reddit_behaviour/commit/aa10349235126203785355b60a4884a5e1c648ae](url). But I am really sorry that I pushed the commit directly to the main.

**Comment by nobbynguyen** [comment]
@LukeAC : Regarding Summary of Addressed Feedback, here is the link to address the 4th comment about author list. 
Actually, we already have the list, it is at the bottom of the report page.
[https://ubc-mds.github.io/covid_reddit_behaviour/introduction.html](url)
